import { useEffect, useRef, useState } from 'react'
import Globe, { type GlobeInstance } from 'globe.gl'
import * as THREE from 'three'
import type { Geo, PFZ, VerdictLevel } from '../types'

// A rotating globe, not a slippy map, and the reason is the question this app
// answers. "Is it safe to fish off Kochi?" is a question about a point on a
// sphere, and a 2D chart of the Indian coast hides the two facts that make the
// answer trustworthy: which sea the point is actually in, and that the
// suggested zone is genuinely offshore of it, at a bearing that differs by
// port. The globe makes both obvious before a single number is read.
//
// It carries no basemap texture on purpose. The obvious move is
// globeImageUrl('...blue-marble.jpg'), and on a machine with an ad blocker the
// request never completes and the globe is either blank or absent — and the
// person who reported it cannot tell you why their screen is different from
// yours. The ocean is drawn into a canvas at runtime instead.
//
// The map is real, though. It is Natural Earth 110m, converted to GeoJSON at
// build time by scripts/build-geo.mjs and committed under public/geo, so it is
// served from this origin and there is nothing left to block. Countries rather
// than landmasses, because the difference between "a blue ball" and "a map" is
// borders and names: one polygon layer stroked per country draws the coastline
// and every internal boundary in the same pass. The thirty-two supported ports
// are plotted on top from the same table the backend resolves against, so a dot
// on the coast is a port ORCA can actually answer for, and the shape of the
// Indian coastline is the reason those dots sit where they do.

const IDLE_POV = { lat: 14, lng: 80, altitude: 2.35 }
const FOCUS_ALTITUDE = 0.85

const VERDICT_COLOR: Record<VerdictLevel, string> = {
  go: '#34d399',
  caution: '#fbbf24',
  'no-go': '#f87171',
}

const COAST_COLOR = '#5eead4'
const PORT_COLOR = '#38bdf8'

// Land sits slightly proud of the ocean rather than painted onto it, so the
// coast reads as a shelf and the shoreline catches the terminator. The colours
// are chosen to sit between the ocean and the sky in value, which keeps the
// ports and the verdict marker as the only saturated things on the sphere.
const LAND_FILL = '#0f2c3d'
const LAND_SIDE = '#0a1f2c'
const LAND_EDGE = '#6f9fb8'

// Country names are deliberately dimmer than the port dots. A globe carries
// dozens of them at once, and the moment they compete with the point the
// question is about, the answer stops being the brightest thing on screen.
const LABEL_COLOR = 'rgba(148, 197, 214, 0.85)'
const PORT_LABEL_COLOR = 'rgba(190, 219, 232, 0.92)'

// A port label sits closest to the surface, because it belongs to a dot that is
// already there; the result label is lifted clear of everything so it reads as
// the answer rather than as another place on the coast.
const PORT_LABEL_ALTITUDE = 0.011

type LabelKind = 'country' | 'port' | 'result'

const LABEL_SIZE: Record<LabelKind, number> = {
  country: 0.46,
  port: 0.4,
  result: 0.66,
}
const LABEL_INK: Record<LabelKind, string> = {
  country: LABEL_COLOR,
  port: PORT_LABEL_COLOR,
  result: COAST_COLOR,
}
const LABEL_HEIGHT: Record<LabelKind, number> = {
  country: 0.009,
  port: PORT_LABEL_ALTITUDE,
  result: 0.015,
}

// Below this camera altitude the port names are legible enough to be worth
// drawing. globe.gl measures altitude as a multiple of the globe radius, so
// 1.6 is roughly "close enough to read a 40 km stretch of coast".
const PORT_LABEL_ALTITUDE_LIMIT = 1.6

// Served from this origin out of web/public/geo, regenerated by
// `npm run build:geo`. The rewrite and cache header for this path live in
// vercel.json; the rewrite there used to swallow /geo and answer with
// index.html, which is the same class of bug as the CDN this avoids.
const GEO_WORLD = `${import.meta.env.BASE_URL}geo/world.json`
const GEO_LABELS = `${import.meta.env.BASE_URL}geo/labels.json`

interface GeoJsonFeature {
  type: string
  properties?: Record<string, string>
  geometry: { type: string; coordinates: number[][][] | number[][][][] }
}

interface CountryLabel {
  name: string
  text: string
  lat: number
  lon: number
}

interface MapLabel extends CountryLabel {
  kind: LabelKind
}

export interface PortDot {
  name: string
  lat: number
  lon: number
  coast: string
}

/**
 * Draws the globe's surface: deep ocean, a soft photic gradient toward the
 * equator, and a graticule every 15 degrees.
 *
 * The graticule is doing real work. Without it a smooth sphere reads as a
 * sphere and gives no sense of scale, so the 45 km between a port and its
 * recommended zone — the single distance the whole product is about — is
 * invisible. A grid makes rotation legible and makes the zoom meaningful.
 */
function oceanTexture(): string {
  const w = 2048
  const h = 1024
  const c = document.createElement('canvas')
  c.width = w
  c.height = h
  const ctx = c.getContext('2d')
  if (!ctx) return ''

  const base = ctx.createLinearGradient(0, 0, 0, h)
  base.addColorStop(0, '#071a2b')
  base.addColorStop(0.5, '#0b2c45')
  base.addColorStop(1, '#071a2b')
  ctx.fillStyle = base
  ctx.fillRect(0, 0, w, h)

  // A faint band of warm water either side of the equator, which is where the
  // PFZ band actually sits. It hints at the thing the scoring is looking for
  // without pretending to be sea-surface temperature.
  const gyre = ctx.createRadialGradient(w / 2, h / 2, 0, w / 2, h / 2, h * 0.62)
  gyre.addColorStop(0, 'rgba(45,212,191,0.10)')
  gyre.addColorStop(1, 'rgba(45,212,191,0)')
  ctx.fillStyle = gyre
  ctx.fillRect(0, 0, w, h)

  ctx.strokeStyle = 'rgba(125,211,252,0.10)'
  ctx.lineWidth = 1
  for (let x = 0; x <= w; x += w / 24) {
    ctx.beginPath()
    ctx.moveTo(x, 0)
    ctx.lineTo(x, h)
    ctx.stroke()
  }
  for (let y = 0; y <= h; y += h / 12) {
    ctx.beginPath()
    ctx.moveTo(0, y)
    ctx.lineTo(w, y)
    ctx.stroke()
  }

  // The equator is the one line worth naming.
  ctx.strokeStyle = 'rgba(94,234,212,0.22)'
  ctx.lineWidth = 2
  ctx.beginPath()
  ctx.moveTo(0, h / 2)
  ctx.lineTo(w, h / 2)
  ctx.stroke()

  return c.toDataURL('image/png')
}

export function Globe3D({
  towns,
  geo,
  pfz,
  level,
  onFail,
}: {
  towns: PortDot[]
  geo: Geo | null
  pfz: PFZ | null
  level: VerdictLevel | null
  onFail?: () => void
}) {
  const host = useRef<HTMLDivElement>(null)
  const globe = useRef<GlobeInstance | null>(null)
  const [ready, setReady] = useState(false)
  const [countryLabels, setCountryLabels] = useState<CountryLabel[]>([])
  // True once the camera is close enough for port names to be legible. Tracked
  // from the zoom callback because the idle globe is two orders of magnitude
  // too far away to read a fishing port from.
  const [zoomedIn, setZoomedIn] = useState(false)

  useEffect(() => {
    const el = host.current
    if (!el || globe.current) return

    // A failed WebGL context does not always throw — some drivers return null
    // from getContext and hand back a renderer that silently draws nothing. A
    // probe is the only way to tell "no WebGL" apart from "a very dark globe",
    // and the difference matters, because one of them should fall back to the
    // 2D chart and the other should not.
    try {
      const probe = document.createElement('canvas')
      const gl = probe.getContext('webgl2') ?? probe.getContext('webgl')
      if (!gl) {
        onFail?.()
        return
      }
      // Free the probe context immediately; browsers cap live WebGL contexts
      // and an extra one left open can cost the real globe its slot.
      gl.getExtension('WEBGL_lose_context')?.loseContext()
    } catch {
      onFail?.()
      return
    }

    let g: GlobeInstance
    try {
      g = new Globe(el, { animateIn: true })
    } catch {
      // No WebGL, a blocked context, or a driver that refuses one. The parent
      // swaps in the 2D chart rather than showing an empty box.
      onFail?.()
      return
    }

    const material = new THREE.MeshPhongMaterial({
      map: (() => {
        const url = oceanTexture()
        if (!url) return null
        const tex = new THREE.TextureLoader().load(url)
        tex.colorSpace = THREE.SRGBColorSpace
        return tex
      })(),
      color: 0xffffff,
      emissive: 0x06121f,
      emissiveIntensity: 0.7,
      shininess: 11,
      specular: new THREE.Color(0x2a6f8f),
    })

    g.backgroundColor('rgba(0,0,0,0)')
      .globeMaterial(material)
      .showAtmosphere(true)
      .atmosphereColor('#4cc9f0')
      .atmosphereAltitude(0.17)
      .globeOffset?.([0, 0])

    const controls = g.controls()
    controls.autoRotate = true
    controls.autoRotateSpeed = 0.45
    controls.enableZoom = true
    controls.enablePan = false
    controls.minDistance = 130
    controls.maxDistance = 620

    g.pointOfView(IDLE_POV, 0)
    globe.current = g

    // globe.gl sizes itself from the container once, so a container that is
    // hidden or zero-height at construction (a lazy chunk arriving during the
    // first paint, a phone rotating) leaves the canvas stuck at the old size.
    // Observing the element keeps it honest.
    const ro = new ResizeObserver(() => {
      g.width(el.clientWidth)
      g.height(el.clientHeight)
    })
    ro.observe(el)

    let cancelled = false
    // onGlobeReady fires after the surface has been uploaded. Deferring the
    // first data write until then avoids a frame where points float over an
    // empty sphere.
    g.onGlobeReady(() => {
      if (!cancelled) setReady(true)
    })

    // Port names are drawn only once the camera is close enough to read them.
    // This covers the user zooming in on the idle globe. The answered-question
    // case is set by the flight itself rather than by this callback, because a
    // programmatic camera move does not fire it.
    g.onZoom((pov) => {
      if (cancelled) return
      setZoomedIn((pov.altitude ?? IDLE_POV.altitude) < PORT_LABEL_ALTITUDE_LIMIT)
    })

    return () => {
      cancelled = true
      ro.disconnect()
      globe.current = null
      setReady(false)
      try {
        g._destructor()
      } catch {
        /* already torn down */
      }
      el.replaceChildren()
    }
  }, [onFail])

  // The map. Fetched from this origin, decoded once, and drawn under everything
  // else. If it fails the globe is still a working globe — an ocean with the
  // right points on it — so this layer never blocks and never reports itself as
  // a failure of the visualisation.
  useEffect(() => {
    const g = globe.current
    if (!g || !ready) return
    let cancelled = false

    const load = async () => {
      // Only the fetch and the parse are allowed to fail quietly. An earlier
      // version wrapped the whole thing in one try, and a typo'd accessor call
      // inside it was swallowed as if the coastline were merely unavailable —
      // the layer silently did nothing and the console stayed clean.
      let world: GeoJsonFeature
      let labels: CountryLabel[]
      try {
        const [w, l] = await Promise.all([fetch(GEO_WORLD), fetch(GEO_LABELS)])
        if (!w.ok || !l.ok) return
        world = (await w.json()) as GeoJsonFeature
        labels = (
          (await l.json()) as { name: string; lat: number; lon: number }[]
        ).map((d) => ({ ...d, text: d.name }))
      } catch {
        return
      }
      if (cancelled) return

      // One layer, doing both jobs: the cap fills each country and the stroke
      // traces the coastline and the borders between countries. A second line
      // layer for the outline was tried and removed — it fed NaN positions into
      // the renderer's bounding-sphere calculation and logged twenty-four
      // warnings, for a line the polygon stroke already draws.
      const features =
        world.type === 'FeatureCollection'
          ? (world as unknown as { features: GeoJsonFeature[] }).features
          : [world]

      g.polygonsData(features)
        .polygonCapColor(() => LAND_FILL)
        .polygonSideColor(() => LAND_SIDE)
        .polygonStrokeColor(() => LAND_EDGE)
        .polygonAltitude(0.007)
        .polygonCapCurvatureResolution(4)

      setCountryLabels(labels)
    }
    void load()

    return () => {
      cancelled = true
      g.polygonsData([])
    }
  }, [ready])

  // Idle layer: every supported port, drawn small. This is the coastline.
  useEffect(() => {
    const g = globe.current
    if (!g || !ready) return
    if (geo) {
      g.pointsData([])
      return
    }
    g.pointsData(towns)
      .pointLat('lat')
      .pointLng('lon')
      .pointColor(() => PORT_COLOR)
      .pointAltitude(0.008)
      .pointRadius(0.16)
      .pointResolution(12)
      .pointLabel((d) => {
        const t = d as PortDot
        return `<div class="globe-tip"><strong>${t.name}</strong><br/><span>${t.coast}</span></div>`
      })
    g.ringsData([])
    g.arcsData([])
  }, [towns, ready, geo])

  // Labels: every country, every supported port, and the place the question is
  // about.
  //
  // These used to be separate layers writing to the same globe.gl property, and
  // the result won: arriving at a verdict wiped every country name off the map,
  // which is the opposite of what a map is for. One effect owns the layer now, so
  // the names stay put and the answer is added to them.
  //
  // The port names are the point of this layer. A dot on a coast says "something
  // is here"; it does not say whether the next bay along is Berhampur or Puri,
  // and on a stretch of coast where the fishing ports are 40 km apart that
  // difference is the whole question. So every supported port is named, not just
  // the one that was asked about.
  useEffect(() => {
    const g = globe.current
    if (!g || !ready) return

    const marks: MapLabel[] = countryLabels.map((l) => ({ ...l, kind: 'country' }))

    // Thirty-six names along one coastline is unreadable from across the globe,
    // where the whole Indian coast is a few dozen pixels. They are therefore
    // shown whenever the camera is close enough for them to be legible, which
    // includes every answered question — arriving at a verdict flies to the
    // coast, and that is precisely when a fisherman wants to see what is
    // nearby. A user who zooms in on the idle globe gets them too.
    if (geo || zoomedIn) {
      for (const t of towns) {
        marks.push({ name: t.name, text: t.name, lat: t.lat, lon: t.lon, kind: 'port' })
      }
    }

    if (geo) {
      marks.push({
        name: 'result',
        text: geo.name || 'Requested point',
        lat: geo.lat,
        lon: geo.lon,
        kind: 'result',
      })
    }

    g.labelsData(marks)
      .labelLat('lat')
      .labelLng('lon')
      .labelText('text')
      .labelSize((d) => LABEL_SIZE[(d as MapLabel).kind])
      .labelDotRadius(0)
      .labelColor((d) => LABEL_INK[(d as MapLabel).kind])
      .labelAltitude((d) => LABEL_HEIGHT[(d as MapLabel).kind])
      .labelIncludeDot(false)
      .labelResolution(2)
  }, [countryLabels, towns, geo, zoomedIn, ready])

  // Result layer: fly to the resolved coast, then draw what was decided.
  useEffect(() => {
    const g = globe.current
    if (!g || !ready) return

    if (!geo) {
      g.controls().autoRotate = true
      g.pointOfView(IDLE_POV, 1200)
      // IDLE_POV sits above the label threshold, so the port names have to come
      // off. A programmatic move does not fire onZoom, so this is not optional
      // bookkeeping: without it the names stay drawn over a globe they are too
      // small to read on, or vanish from a close-up after the next question.
      setZoomedIn(false)
      return
    }

    const color = level ? VERDICT_COLOR[level] : COAST_COLOR
    const zLat = pfz?.lat ?? geo.way_lat
    const zLon = pfz?.lon ?? geo.way_lon
    const hasZone = Boolean(pfz && (pfz.lat !== 0 || pfz.lon !== 0))

    g.controls().autoRotate = false
    g.pointOfView({ lat: geo.lat, lng: geo.lon, altitude: FOCUS_ALTITUDE }, 1600)
    // The flight lands closer than the label threshold, so the port names belong
    // on screen. onZoom does not fire for a programmatic move, so without this
    // the camera arrives at a coastline with no port on it — the one moment the
    // names are most useful. Derived from the target altitude rather than set to
    // a literal, so the two cannot drift apart if FOCUS_ALTITUDE ever moves
    // across the threshold.
    setZoomedIn(FOCUS_ALTITUDE < PORT_LABEL_ALTITUDE_LIMIT)

    const coast = {
      name: geo.name || 'Requested point',
      lat: geo.lat,
      lon: geo.lon,
      coast: 'Coast',
    }
    const zone = { name: 'Suggested zone', lat: zLat, lon: zLon, coast: 'Offshore' }

    g.pointsData(hasZone ? [coast, zone] : [coast])
      .pointLat('lat')
      .pointLng('lon')
      .pointColor((d) => ((d as PortDot).name === 'Suggested zone' ? color : COAST_COLOR))
      .pointAltitude((d) => ((d as PortDot).name === 'Suggested zone' ? 0.02 : 0.012))
      .pointRadius((d) => ((d as PortDot).name === 'Suggested zone' ? 0.42 : 0.3))
      .pointResolution(20)
      .pointLabel((d) => {
        const t = d as PortDot
        return `<div class="globe-tip"><strong>${t.name}</strong><br/><span>${t.coast}</span></div>`
      })

    g.arcsData(hasZone ? [{ startLat: geo.lat, startLng: geo.lon, endLat: zLat, endLng: zLon }] : [])
      .arcColor(() => [COAST_COLOR, color])
      .arcStroke(0.55)
      .arcAltitudeAutoScale(0.35)
      .arcDashLength(0.4)
      .arcDashGap(0.18)
      .arcDashAnimateTime(2400)

    // A pulse on the zone. The animation is the cheapest way to say "this is
    // the thing the answer is about" without a legend.
    g.ringsData(hasZone ? [{ lat: zLat, lng: zLon }] : [])
      .ringLat('lat')
      .ringLng('lng')
      .ringColor(() => (t: number) => {
        const c = new THREE.Color(color)
        return `rgba(${Math.round(c.r * 255)},${Math.round(c.g * 255)},${Math.round(c.b * 255)},${1 - t})`
      })
      .ringMaxRadius(3.4)
      .ringPropagationSpeed(1.1)
      .ringRepeatPeriod(1400)
  }, [geo, pfz, level, ready])

  return <div ref={host} className="globe-host" aria-hidden="true" />
}
